version: '3.4'

services:
  storecontrol.webapi:
    image: ${DOCKER_REGISTRY-}storecontrolwebapi
    container_name: storecontrol.webapi
    build:
      context: .
      dockerfile: StoreControl.WebAPI/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=storecontrol.database;Port=5432;Database=StoreControl;Username=postgres;Password=postgres;Include Error Detail=true 

  storecontrol.database:
    image: postgres:latest
    container_name: storecontrol.database
    environment:
      - POSTGRES_DB=StoreControl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  storecontrol.pgadmin:
    image: dpage/pgadmin4:latest
    container_name: storecontrol.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
      - PGADMIN_LISTEN_PORT=5000
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5000:5000"

  storecontrol.seq:
    image: datalust/seq:latest
    container_name: storecontrol.seq
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    ports:
      - 5341:5341
      - 80:80

volumes:
  database-data:
  pgadmin-data:
  seq-data:
